added deploy script for multiple bitcoind

diff --git a/bin/b b/bin/b
--- a/bin/b
+++ b/bin/b
@@ -128,7 +128,62 @@ X=1
 while [[ $X -le $INSTANCE_COUNT ]]
 do
   TAG_ID_INSTANCE="${TAG_ID}_${X}"
-  echo "TAG_ID_INSTANCE=${TAG_ID_INSTANCE}"
+
+  for i in ` (docker ps --format '{{.ID}};{{.Names}}' 2>&1) | grep ";${TAG_ID_INSTANCE}$"`
+  do
+    CONTAINER_ID=`echo ${i} | cut -d';' -f1`
+    if [[ "${REMOVE}" == "Y" ]]
+    then
+      echo "stopping container '${CONTAINER_ID}'"
+      docker stop "${CONTAINER_ID}" 2>/dev/null
+      sleep 5
+    else
+      CONTAINER_NAME=`echo ${i} | cut -d';' -f2`
+      echo "error: not stopped container ${CONTAINER_ID} / ${CONTAINER_NAME} already exists"
+      exit 1
+    fi
+  done
+
+  for i in ` (docker ps --all --format '{{.ID}};{{.Names}}' 2>&1) | grep ";${TAG_ID_INSTANCE}$"`
+  do
+    CONTAINER_ID=`echo ${i} | cut -d';' -f1`
+    if [[ "${REMOVE}" == "Y" ]]
+    then
+      echo "removing container '${CONTAINER_ID}'"
+      docker rm "${CONTAINER_ID}"
+      sleep 5
+    else
+      CONTAINER_NAME=`echo ${i} | cut -d';' -f2`
+      echo "error: not removed container ${CONTAINER_ID} / ${CONTAINER_NAME} already exists"
+      exit 1
+    fi
+  done
 
   let X=$((X + 1))
 done
+
+X=1
+
+HTTP_EXTERNAL_PORT_N=$HTTP_EXTERNAL_PORT
+SSH_EXTERNAL_PORT_N=$SSH_EXTERNAL_PORT
+BITCOIN_EXTERNAL_PORT_N=$BITCOIN_EXTERNAL_PORT
+
+docker ps --all
+
+while [[ $X -le $INSTANCE_COUNT ]]
+do
+  TAG_ID_INSTANCE="${TAG_ID}_${X}"
+
+  HTTP_EXTERNAL_PORT_N=$((HTTP_EXTERNAL_PORT_N + 1))
+  SSH_EXTERNAL_PORT_N=$((SSH_EXTERNAL_PORT_N + 1))
+  BITCOIN_EXTERNAL_PORT_N=$((BITCOIN_EXTERNAL_PORT_N + 1))
+
+  docker run --name "${TAG_ID_INSTANCE}" -d -p "${HTTP_EXTERNAL_PORT_N}:${HTTP_INTERNAL_PORT}" \
+   -p "${SSH_EXTERNAL_PORT_N}:${SSH_INTERNAL_PORT}" -p "${BITCOIN_EXTERNAL_PORT_N}:${BITCOIN_INTERNAL_PORT}" \
+   "$TAG_PREFIX"
+
+  let X=$((X + 1))
+done
+
+docker ps --all
+
